:- module(suturo_test,
          [ test_setup/0,
            test_cleanup/0
          ]).

% useful stuff for testing suturo_knowledge code.

% setup and cleanup make sure all data generated by the test are dropped.
:- dynamic old_default/1.

test_setup :-
    lang_query:default_graph(OldDefault),
    assertz(old_default(OldDefault)),
    lang_query:set_default_graph(test_user).

test_cleanup :-
    drop_graph(test_user),
    old_default(OldDefault),
    retract(old_default(OldDefault)),
    lang_query:set_default_graph(OldDefault).
