name: Extract NL Names

on:
  push:
    branches:
      - master
    paths:
      - "path_to_your_owl_file1.owl"
      - "path_to_your_owl_file2.owl"
      - ".github/workflows/extract_nl_names.yml"
  workflow_dispatch:

jobs:
  extract_nl_names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rdflib pyyaml

      - name: Run extraction script
        run: python extract_nl_names.py path_to_your_owl_file1.owl path_to_your_owl_file2.owl

      - name: Upload extraction output
        uses: actions/upload-artifact@v3
        with:
          name: extraction-output
          path: output_entities.yml

  publish:
    runs-on: ubuntu-latest
    needs: extract_nl_names

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.event.head_commit.author.name }}"
          git config --global user.email "${{ github.event.head_commit.author.email }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download extraction output artifacts
        uses: actions/download-artifact@v3
        with:
          name: extraction-output
          path: docs/objects/extraction/output/

      - name: Commit and push extraction output artifacts
        run: |
          # Only commit if there are changes in the extraction output directory
          if [[ $(git status --porcelain -- docs/objects/extraction/output/) ]]; then
            git add docs/objects/extraction/output/*
            git commit -m "Updated extraction output to $(echo ${GITHUB_SHA} | cut -c1-7) (${{ github.workflow }}:${{ github.run_number }} :rocket:)"
            git push origin master

            # Trigger the mkdocs workflow to build and deploy the website with the new artifacts
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/suturo/suturo_knowledge/actions/workflows/mkdocs.yml/dispatches \
              -d '{"ref": "master"}'
          else
            echo "No changes detected in extraction output directory. Skipping commit and push to website."
          fi
