name: Generate docs

on:
  push:
    branches:
      - robocup
  workflow_dispatch:

env:
  OWL2ANYTHING_VERSION: 1.4.1

jobs:

  owl2anything:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Download owl2anything
        run: |
          curl -L -o owl2anything.zip https://github.com/SUTURO/Owl2Anything/releases/download/$OWL2ANYTHING_VERSION/owl2anything-$OWL2ANYTHING_VERSION.zip
          unzip owl2anything.zip

      - name: Run owl2anything
        run: java -jar owl2anything-$OWL2ANYTHING_VERSION/owl2anything-$OWL2ANYTHING_VERSION.jar -i "suturo_knowledge/owl/suturo.owl" --root "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#PhysicalObject" --mapping "owl2anything-$OWL2ANYTHING_VERSION/owl2anything/iri_mapping_default.csv" --namespaces "owl2anything-$OWL2ANYTHING_VERSION/owl2anything/iri_namespaces_default.csv"

      - name: Upload owl2anything output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            owl2anything/output/*

  extract_nl_names:
    runs-on: ubuntu-latest
    needs: owl2anything

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rdflib pyyaml

      - name: Run extraction script
        run: python3 $GITHUB_WORKSPACE/suturo_knowledge/scripts/extract_nl_names.py $GITHUB_WORKSPACE/suturo_knowledge/owl/suturo.owl

      - name: Upload extraction output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: nlp_entities.yml

  publish:
    runs-on: ubuntu-latest
    needs: extract_nl_names

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.event.head_commit.author.name }}"
          git config --global user.email "${{ github.event.head_commit.author.email }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download extraction output artifacts
        uses: actions/download-artifact@v3
        with:
          name: output
          path: docs/objects/owl2anything/output/

      - name: Commit and push extraction output artifacts
        run: |
          # Only commit if there are changes in the extraction output directory
          if [[ $(git status --porcelain -- docs/objects/owl2anything/output/) ]]; then
            git add docs/objects/owl2anything/output/*
            git commit -m "Updated extraction output to $(echo ${GITHUB_SHA} | cut -c1-7) (${{ github.workflow }}:${{ github.run_number }} :rocket:)"
            git push origin robocup

            # Trigger the mkdocs workflow to build and deploy the website with the new artifacts
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/suturo/suturo_knowledge/actions/workflows/mkdocs.yml/dispatches \
              -d '{"ref": "robocup"}'
          else
            echo "No changes detected in extraction output directory. Skipping commit and push to website."
          fi
